--
-- SCRIPT D_Mobile_Billing_Cycle, entity for URM
-- Engine: Teradata
-- Server: 10.167.37.107
-- DB: AR_PROD_ODS_DATA_VW
-- Owner: Big Data, Telefonica Argentina
--

SELECT
 '722-070'	AS	OPERATOR_ID
, NULL AS	BILLING_CYCLE_CLOSE_DT
, BCI.BILLING_CYCLE_KEY AS	BILLING_CYCLE_ID
, UPPER(BC.BILLING_CYCLE_DESC)	 AS	BILLING_CYCLE_DES	
, (10000*EXTRACT(YEAR FROM (BCI.START_DATE))+100*EXTRACT(MONTH FROM (BCI.START_DATE))+EXTRACT(DAY FROM (BCI.START_DATE))) AS BILLING_CYCLE_START_DT	
, (10000*EXTRACT(YEAR FROM (BCI.END_DATE))+100*EXTRACT(MONTH FROM (BCI.END_DATE))+EXTRACT(DAY FROM (BCI.END_DATE))) AS	BILLING_CYCLE_END_DT	
, CASE WHEN BCI.DUE_DATE<BCI.END_DATE 
			THEN  (10000*EXTRACT(YEAR FROM (BCI.END_DATE + INTERVAL '22' DAY))+100*EXTRACT(MONTH FROM (BCI.END_DATE + INTERVAL '22' DAY))+EXTRACT(DAY FROM (BCI.END_DATE + INTERVAL '22' DAY))) 
			ELSE (10000*EXTRACT(YEAR FROM (BCI.DUE_DATE))+100*EXTRACT(MONTH FROM (BCI.DUE_DATE))+EXTRACT(DAY FROM (BCI.DUE_DATE))) 
  END  AS	BILLING_DUE_DT	
,NULL AS	BILLING_RV_COMPUTES_CD
,(10000*EXTRACT(YEAR FROM (BCI.END_DATE + INTERVAL '1' DAY))+100*EXTRACT(MONTH FROM (BCI.END_DATE + INTERVAL '1' DAY))+1)  BILLING_ATTRIBUTED_END_DT
FROM 
AR_PROD_ODS_DATA_VW.BILLING_CYCLE_INSTANCE BCI
INNER JOIN BILLING_CYCLE BC ON BC.BILLING_CYCLE_KEY=BCI.BILLING_CYCLE_KEY
where 100*BCI.CYCLE_YEAR+BCI.CYCLE_INSTANCE >= 201001
ORDER BY  100*BCI.CYCLE_YEAR+BCI.CYCLE_INSTANCE,BCI.BILLING_CYCLE_KEY