--
-- SCRIPT AR_D_Offering_Category, entity for URM
-- Engine: Teradata
-- Server: 10.167.37.107
-- DB: AR_PROD_ODS_DATA_VW
-- Owner: Big Data, Telefonica Argentina

SELECT 	'722-070' AS OPERATOR_ID,
	PRODUCT_CATALOG_TYPE_KEY AS OFFERING_CATEGORY_ID,
	PRODUCT_CATALOG_TYPE_DESC AS OFFERING_CATEGORY_INTERNAL_DES ,
	PRODUCT_CATALOG_TYPE_DESC AS OFFERING_CATEGORY_COMMERCIAL_DES
FROM AR_PROD_ODS_DATA_VW.PRODUCT_CATALOG_TYPE
GROUP BY 2,3,4
ORDER BY 2,3,4;




