--
-- SCRIPT D_Geographical_Area_Rel, entity for URM
-- Engine: Teradata
-- Server: 10.167.37.107
-- DB: AR_PROD_ODS_DATA_VW
-- Owner: Big Data, Telefonica Argentina
--

SELECT 
 CHILD_GEO_AREA_ID
, GEO_AREA_TYPE_ID
, PARENT_GEO_AREA_ID
,'722-070' AS OPERATOR_ID
FROM 
(
SELECT 
COUNTRY_KEY AS CHILD_GEO_AREA_ID
,1 AS GEO_AREA_TYPE_ID
,-1000 AS PARENT_GEO_AREA_ID  -- el -1000 es porque me tira overflow con valores de menos de 4 digitos
 FROM AR_PROD_ODS_DATA_VW.COUNTRY
UNION ALL
SELECT 
STATE_KEY AS  CHILD_GEO_AREA_ID
,2 AS GEO_AREA_TYPE_ID
,NVL(COUNTRY_KEY,0)  AS PARENT_GEO_AREA_ID
FROM AR_PROD_ODS_DATA_VW.STATE
UNION ALL
SELECT
CITY_KEY AS  CHILD_GEO_AREA_ID
,3 AS GEO_AREA_TYPE_ID
,NVL(STATE_KEY,0) AS PARENT_GEO_AREA_ID
FROM AR_PROD_ODS_DATA_VW.CITY
) AS GEO
order by 1,2,3



