--
-- SCRIPT D_Tax, entity for URM
-- Engine: Teradata
-- Server: 10.167.37.107
-- DB: AR_PROD_ODS_DATA_VW
-- Owner: Big Data, Telefonica Argentina
--
SELECT
'722-070' AS OPERATOR_ID
,100*EXTRACT(YEAR FROM CURRENT_DATE)+EXTRACT(MONTH FROM CURRENT_DATE)  AS MONTH_DT  
,TAX_TYPE_KEY AS TAX_RATE_TYPE_CD
,TAX_TYPE_DESC AS TAX_RATE_DES
FROM AR_PROD_ODS_DATA_VW.TAX_TYPE
order by 3,4