--
-- SCRIPT D_Payment_Method, entity for URM
-- Engine: Teradata
-- Server: 10.167.37.107
-- DB: AR_PROD_ODS_DATA_VW
-- Owner: Big Data, Telefonica Argentina

SELECT	'722-070'	AS	OPERATOR_ID	,
	PAYMENT_METHOD_KEY	AS	PAYMENT_METHOD_CD	,
	PAYMENT_METHOD_DESC	AS	PAYMENT_METHOD_DES	
FROM 	AR_PROD_ODS_DATA_VW.PAYMENT_METHOD
GROUP BY 2,3
ORDER BY 2,3	;	
