--
-- SCRIPT D_Geographical_Area, entity for URM
-- Engine: Teradata
-- Server: 10.167.37.107
-- DB: AR_PROD_ODS_DATA_VW
-- Owner: Big Data, Telefonica Argentina
--

SELECT 
OPERATOR_ID
, GEO_AREA_ID
, GEO_AREA_TYPE_ID
, GEO_AREA_NAME
,CASE WHEN GEO_AREA_ID=41150 THEN	'A—ELO'
			WHEN GEO_AREA_ID=87429 THEN 'SAENZ PE—A'
			WHEN GEO_AREA_ID=76952 THEN 'GUA—ACOS'
			WHEN GEO_AREA_ID=89464 THEN '	SAENZ PE—A'
			WHEN GEO_AREA_ID=54264 THEN 'SAN PEDRO DEL CHA—AR'
 ELSE GEO_AREA_NAME END AS GEO_AREA_NAME
, HOME_POPULATION_NUM
, WORKING_POPULATION_NUM
, CENSUS_ATTRIB_A_DES, CENSUS_ATTRIB_B_DES
, CENSUS_ATTRIB_C_DES, HOUSEHOLD_COUNT_NUM
FROM 
(SELECT '722-070' AS OPERATOR_ID
,COUNTRY_KEY AS  GEO_AREA_ID
,1 AS GEO_AREA_TYPE_ID
,TRIM(BOTH FROM REGEXP_SUBSTR(UPPER(COUNTRY_DESC),'[a-zA-Z0-9¡…Õ”⁄—‹\ ]+')) AS GEO_AREA_NAME
,0 AS HOME_POPULATION_NUM
,0 AS WORKING_POPULATION_NUM
,'' AS CENSUS_ATTRIB_A_DES
,'' AS CENSUS_ATTRIB_B_DES
,'' AS CENSUS_ATTRIB_C_DES
,0 AS HOUSEHOLD_COUNT_NUM
 FROM AR_PROD_ODS_DATA_VW.COUNTRY
UNION ALL
SELECT '722-070' AS OPERATOR_ID
,STATE_KEY AS  GEO_AREA_ID
,2 AS GEO_AREA_TYPE_ID
,TRIM(BOTH FROM REGEXP_SUBSTR(UPPER(STATE_DESC),'[a-zA-Z0-9¡…Õ”⁄—‹\ ]+')) AS GEO_AREA_NAME
,0 AS HOME_POPULATION_NUM
,0 AS WORKING_POPULATION_NUM
,'' AS CENSUS_ATTRIB_A_DES
,'' AS CENSUS_ATTRIB_B_DES
,'' AS CENSUS_ATTRIB_C_DES
,0 AS HOUSEHOLD_COUNT_NUM
FROM AR_PROD_ODS_DATA_VW.STATE
UNION ALL
SELECT '722-070' AS OPERATOR_ID
,CITY_KEY AS  GEO_AREA_ID
,3 AS GEO_AREA_TYPE_ID
,TRIM(BOTH FROM REGEXP_SUBSTR(UPPER(CITY_DESC),'[a-zA-Z0-9¡…Õ”⁄—‹\ ]+')) AS GEO_AREA_NAME
,0 AS HOME_POPULATION_NUM
,0 AS WORKING_POPULATION_NUM
,'' AS CENSUS_ATTRIB_A_DES
,'' AS CENSUS_ATTRIB_B_DES
,'' AS CENSUS_ATTRIB_C_DES
,0 AS HOUSEHOLD_COUNT_NUM
FROM AR_PROD_ODS_DATA_VW.CITY
) AS GEO
ORDER BY GEO_AREA_ID ASC;