--
-- SCRIPT D_AgeSegment, entity for URM
-- Engine: Teradata
-- Server: 10.167.37.107
-- DB: AR_PROD_ODS_DATA_VW
-- Owner: Big Data, Telefonica Argentina
--
SELECT 
'722-070' AS OPERATOR_ID
,10000*EXTRACT(YEAR FROM CURRENT_DATE)+100*EXTRACT( MONTH FROM CURRENT_DATE)+EXTRACT( DAY FROM CURRENT_DATE) AS AGE_SEGMENT_DT
, CASE  
WHEN EXTRACT(YEAR FROM S.SUBSCRIBER_BIRTH_DATE) < 1946  THEN 1
WHEN EXTRACT(YEAR FROM S.SUBSCRIBER_BIRTH_DATE) BETWEEN 1946 AND 1964 THEN 2
WHEN EXTRACT(YEAR FROM S.SUBSCRIBER_BIRTH_DATE) BETWEEN 1965 AND 1978 THEN 3
WHEN EXTRACT(YEAR FROM S.SUBSCRIBER_BIRTH_DATE) BETWEEN 1979 AND 1996 THEN 4
WHEN EXTRACT(YEAR FROM S.SUBSCRIBER_BIRTH_DATE) > 1996   THEN 5
ELSE -1 END AS AGE_SEGMENT_CD
, CASE  
WHEN EXTRACT(YEAR FROM S.SUBSCRIBER_BIRTH_DATE) < 1946  THEN 'Adultomayor, nacidos antes de 1946'
WHEN EXTRACT(YEAR FROM S.SUBSCRIBER_BIRTH_DATE) BETWEEN 1946 AND 1964 THEN 'Babyboomer, nacidos entre 1946 y 1964'
WHEN EXTRACT(YEAR FROM S.SUBSCRIBER_BIRTH_DATE) BETWEEN 1965 AND 1978 THEN 'Generacionx, nacidos entre 1965 y 1978'
WHEN EXTRACT(YEAR FROM S.SUBSCRIBER_BIRTH_DATE) BETWEEN 1979 AND 1996 THEN 'Millennial, nacidos entre 1979 y 1996'
WHEN EXTRACT(YEAR FROM S.SUBSCRIBER_BIRTH_DATE) > 1996   THEN 'Generacionz, nacidos depues de 1996'
ELSE 'NI' END AS AGE_SEGMENT_DES
FROM  AR_PROD_ODS_DATA_VW.SUBSCRIBERS S 
SAMPLE  2000
GROUP BY 2,3,4