--
-- SCRIPT D_Mobile_line_type, entity for URM
-- Engine: Teradata
-- Server: 10.167.37.107
-- DB: AR_PROD_ODS_DATA_VW
-- Owner: Big Data, Telefonica Argentina
--
SELECT
'722-07' AS OPERATOR_ID
, CASE
 WHEN UPPER(INSTANCE_NAME)IN('MOVIL') THEN 1
 WHEN UPPER(INSTANCE_NAME)IN('GSM SUBSCRIPTION') THEN 2
 WHEN UPPER(INSTANCE_NAME)IN('INTERNET MOVIL') THEN 3
 WHEN UPPER(INSTANCE_NAME)IN('INTERNET DIAL UP') THEN 4
 WHEN UPPER(INSTANCE_NAME)IN('MEC') THEN 5
 WHEN UPPER(INSTANCE_NAME)IN('APLICACIONES DIGITALES') THEN 6
ELSE -1 END AS LINE_TYPE_ID 
, CASE WHEN COALESCE(UPPER(INSTANCE_NAME), 'N/A')  IN ('MOVIL','GSM SUBSCRIPTION','INTERNET MOVIL','INTERNET DIAL UP','MEC','APLICACIONES DIGITALES') 
     THEN INSTANCE_NAME 
     ELSE 'N/A' END AS LINE_TYPE_DES 
,CASE
 WHEN UPPER(INSTANCE_NAME)IN('MOVIL','GSM SUBSCRIPTION') THEN 1
 WHEN UPPER(INSTANCE_NAME)IN('INTERNET MOVIL','INTERNET DIAL UP') THEN 2
 WHEN UPPER(INSTANCE_NAME)='MEC' THEN 3
 WHEN UPPER(INSTANCE_NAME)='APLICACIONES DIGITALES' THEN 4
ELSE -1 END AS GBL_MOBILE_LINE_TYPE_ID
FROM (SELECT INSTANCE_NAME
 FROM AR_PROD_ODS_DATA_VW.SUBSCRIBERS
 GROUP BY INSTANCE_NAME) AS TB
GROUP BY 2,3,4
ORDER BY 2,3,4 ;